### PR TITLE
Change JMS serializer version to 1.0

### PR DESCRIPTION
**Pull request by sroze**
In the case you merge SimpleBus/JMSSerializerBridge#2 and then tag the version 1.1 for `JMSSerializerBridge`, here's the PR that upgrade the bundle :)

### CODE REVIEW

**Comment by sroze** [comment]
@matthiasnoback updated PR to allow 1.0 of `jms/serializer-bundle` instead of replacing with.

**Comment by matthiasnoback** [comment]
If I'm not mistaken, composer would've picked 1.0, but the Travis build doesn't show this. Looking at https://getcomposer.org/doc/articles/versions.md it seems that instead of `|`, `||` should be used. Could you try that please? Also for the bundle?

**Comment by sroze** [comment]
@matthiasnoback you're right, I've updated on the both PRs.

**Comment by matthiasnoback** [comment]
Thanks! Just merged and tagged new (patch) versions for both libraries.

**Comment by sroze** [comment]
Great, thanks ! :+1:

**Pull request merged**
